### 新增用户
POST http://{{baseUrl}}/user
Content-Type: application/json

{
  "userCO" : {
    "name":"王五2",
    "sexCode":1,
    "sex":"男",
    "mobile":"123110111"
  }
}

### 查询用户list
GET http://{{baseUrl}}/users/list
Content-Type: application/json

{
  "sex": 1
}

### 查询用户page
GET http://{{baseUrl}}/users/page
Content-Type: application/json

{
  "pageIndex": 2,
  "pageSize": 3
}

### 根据姓名查询用户
GET http://{{baseUrl}}/user?name=张三
Accept: application/json

### 更新用户
PUT http://{{baseUrl}}/user
Content-Type: application/json

{
  "userCO" : {

    "name":"王五1",
    "sexCode":1,
    "sex":"男",
    "mobile":"123110111"
  }
}