package com.jiuv.cornerstone.user.gatewayimpl.database;

import com.jiuv.cornerstone.user.gatewayimpl.database.dataobject.UserDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jul 01 14:53:15 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jul 01 14:53:15 CST 2021
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jul 01 14:53:15 CST 2021
     */
    UserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jul 01 14:53:15 CST 2021
     */
    List<UserDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jul 01 14:53:15 CST 2021
     */
    int updateByPrimaryKey(UserDO record);

    UserDO selectByName(String name);

    List<UserDO> selectBySex(Integer sex);
}